#!/bin/zsh
# Regenerates THIRD-PARTY-NOTICES.md from the licences actually installed.
#
#   Scripts/make-notices.sh
#
# The app bundles libtorrent, OpenSSL and (compiled in) Boost, and Sparkle once
# it lands. Every one of those licences requires its notice to travel with a
# binary distribution — an obligation that attached the moment the bundling work
# made them ship inside Current.app rather than being loaded from Homebrew.
#
# Generated rather than hand-written on purpose. A notices file pasted from
# memory goes stale the first time a dependency moves, and being confidently
# wrong about someone's licence is worse than not having the file.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/THIRD-PARTY-NOTICES.md"

say() { print -P "%F{cyan}==>%f $1" }
die() { print -P "%F{red}error:%f $1" >&2; exit 1 }

# name|brew formula|licence file inside the prefix|what it is / how it ships
components=(
  "libtorrent-rasterbar|libtorrent-rasterbar|LICENSE|The BitTorrent engine. Ships as a dylib inside Contents/Frameworks."
  "OpenSSL|openssl@3|LICENSE.txt|TLS and crypto, used by libtorrent for HTTPS trackers and peer encryption. Ships as libssl and libcrypto inside Contents/Frameworks."
)

say "Collecting licences"
tmp="$(mktemp)"
{
  print "# Third-party notices"
  print ""
  print "Current is MIT licensed (see [LICENSE](LICENSE)). It **redistributes** the"
  print "components below inside \`Current.app\`, each of which carries its own licence."
  print "Their full texts follow, as those licences require."
  print ""
  print "This file is generated — run \`Scripts/make-notices.sh\` after changing or"
  print "upgrading a dependency. Do not edit it by hand."
  print ""
  print "| Component | Version | Licence |"
  print "| --- | --- | --- |"
} >> "$tmp"

# First pass: the table.
for entry in "${components[@]}"; do
  name="${entry%%|*}"; rest="${entry#*|}"
  formula="${rest%%|*}"; rest="${rest#*|}"
  file="${rest%%|*}"
  prefix="$(brew --prefix "$formula" 2>/dev/null || true)"
  [[ -n "$prefix" && -f "$prefix/$file" ]] || die "no licence at $prefix/$file — is $formula installed?"
  version="$(basename "$(readlink "$prefix" 2>/dev/null || echo "$prefix")")"
  spdx="$(brew info --json=v2 "$formula" 2>/dev/null \
          | python3 -c 'import json,sys;print(json.load(sys.stdin)["formulae"][0].get("license") or "see text")' 2>/dev/null || echo "see text")"
  print "| $name | $version | $spdx |" >> "$tmp"
done

# Boost is a special case: header-only for the parts libtorrent uses, so it is
# compiled *into* the engine rather than shipped as its own file. It still has
# to be acknowledged — the code is in the binary either way.
print "| Boost | headers, compiled into libtorrent | BSL-1.0 |" >> "$tmp"
print "" >> "$tmp"

# Second pass: the full texts.
for entry in "${components[@]}"; do
  name="${entry%%|*}"; rest="${entry#*|}"
  formula="${rest%%|*}"; rest="${rest#*|}"
  file="${rest%%|*}"; note="${rest#*|}"
  prefix="$(brew --prefix "$formula")"
  {
    print "---"
    print ""
    print "## $name"
    print ""
    print "$note"
    print ""
    print '```'
    cat "$prefix/$file"
    print '```'
    print ""
  } >> "$tmp"
  say "  $name"
done

{
  print "---"
  print ""
  print "## Boost"
  print ""
  print "Used by libtorrent. The parts it uses are header-only, so Boost is compiled"
  print "into the engine rather than shipped as a separate file — the code travels in"
  print "the binary regardless, so the notice travels with it."
  print ""
  print '```'
  print "Boost Software License - Version 1.0 - August 17th, 2003"
  print ""
  print "Permission is hereby granted, free of charge, to any person or organization"
  print "obtaining a copy of the software and accompanying documentation covered by"
  print "this license (the \"Software\") to use, reproduce, display, distribute,"
  print "execute, and transmit the Software, and to prepare derivative works of the"
  print "Software, and to permit third-parties to whom the Software is furnished to"
  print "do so, all subject to the following:"
  print ""
  print "The copyright notices in the Software and this entire statement, including"
  print "the above license grant, this restriction and the following disclaimer,"
  print "must be included in all copies of the Software, in whole or in part, and"
  print "all derivative works of the Software, unless such copies or derivative"
  print "works are solely in the form of machine-executable object code generated by"
  print "a source language processor."
  print ""
  print "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"
  print "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"
  print "FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT"
  print "SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE"
  print "FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,"
  print "ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER"
  print "DEALINGS IN THE SOFTWARE."
  print '```'
} >> "$tmp"

mv "$tmp" "$OUT"
say "Wrote ${OUT:t} ($(wc -l < "$OUT" | tr -d ' ') lines)"
print "  Copied into the bundle by Scripts/make-app.sh."
